const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const landingDir = path.join(rootDir, 'apps', 'landing');

const htmlPath = path.join(landingDir, 'index.html');
const jsPath = path.join(landingDir, 'script.js');
const cssPath = path.join(landingDir, 'styles.css');
const cnamePath = path.join(landingDir, 'CNAME');

if (!fs.existsSync(htmlPath) || !fs.existsSync(jsPath) || !fs.existsSync(cssPath)) {
  console.error('[FAIL] Missing landing page core assets in apps/landing.');
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf8');
const js = fs.readFileSync(jsPath, 'utf8');
const css = fs.readFileSync(cssPath, 'styles.css' in fs ? 'utf8' : 'utf8');
const cname = fs.existsSync(cnamePath) ? fs.readFileSync(cnamePath, 'utf8').trim() : '';

if (cname !== 'cipherv.online') {
  console.error(`[FAIL] CNAME is '${cname}', expected 'cipherv.online'.`);
  process.exit(1);
}
console.log(`[PASS] CNAME verified: '${cname}'`);

const idMatches = Array.from(js.matchAll(/getElementById\(['"]([^'"]+)['"]\)/g)).map(m => m[1]);
const uniqueIds = [...new Set(idMatches)];

let missing = 0;
for (const id of uniqueIds) {
  if (!html.includes(`id="${id}"`) && !html.includes(`id='${id}'`)) {
    console.error(`[ERROR] Missing ID in HTML: ${id}`);
    missing++;
  }
}

if (missing === 0) {
  console.log(`[PASS] All ${uniqueIds.length} element IDs referenced in script.js exist in index.html!`);
} else {
  console.error(`[FAIL] ${missing} IDs missing.`);
  process.exit(1);
}

// Check key styles
const keyClasses = [
  'theme-pill-btn', 'tui-tab-btn', 'step-pill', 'chunk-cell',
  'tui-guardian-check', 'shamir-guardian-box', 'snippet-tab', 'cmd-pill',
  'gauge-bar-fill', 'crt-scanlines', 'term-out-line', 'hero-kicker-strip',
  'tui-pillars-grid', 'pillar-card'
];

for (const cls of keyClasses) {
  if (!css.includes(`.${cls}`)) {
    console.error(`[ERROR] Missing CSS class in styles.css: .${cls}`);
    process.exit(1);
  }
}

console.log('[PASS] Core CSS classes verified in styles.css!');

// --- Real-crypto-core regression test --------------------------------------
// The landing workstations must execute genuine algorithms (exact ports of the
// Rust implementation), never canned transcripts. These vectors pin that:
// SHA-256/CRC32 FIPS vectors, GF(2^8) field properties, Shamir round-trips,
// FastCDC determinism + boundary preservation, and cut points generated by
// the REAL Rust chunker (crates/snapshot/src/fastcdc.rs) for fixed payloads.
// Refresh the Rust vectors only from an actual `fastcdc_chunk` run.
global.document = { addEventListener() {} };
const cv = require(path.join(landingDir, 'script.js'));

function assertCore(cond, label) {
  if (!cond) {
    console.error(`[FAIL] Landing crypto core: ${label}`);
    process.exit(1);
  }
}

const te = new TextEncoder();
assertCore(
  cv.cvSha256Hex(new Uint8Array(0)) === 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  'SHA-256("") vector'
);
assertCore(
  cv.cvSha256Hex(te.encode('abc')) === 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
  'SHA-256("abc") vector'
);
assertCore(cv.cvCrc32(te.encode('123456789')) === 0xCBF43926, 'CRC32-IEEE vector');
assertCore(cv.cvGfMul(1, 42) === 42, 'GF(2^8) multiply by one');
let invOk = true;
for (let x = 1; x <= 255; x++) {
  if (cv.cvGfMul(x, cv.cvGfInv(x)) !== 1) { invOk = false; break; }
}
assertCore(invOk, 'GF(2^8) inversion for all 255 nonzero elements');

const crypto = require('crypto');
const secret = new Uint8Array(32);
crypto.randomFillSync(secret);
const shares23 = cv.cvShamirSplit(Buffer.from(secret), 2, 3);
const recovered12 = cv.cvShamirCombine([shares23[0], shares23[1]]);
assertCore(Buffer.from(recovered12).equals(Buffer.from(secret)), 'Shamir 2-of-3 reconstructs');
const shares35 = cv.cvShamirSplit(Buffer.from(secret), 3, 5);
const recovered024 = cv.cvShamirCombine([shares35[0], shares35[2], shares35[4]]);
assertCore(Buffer.from(recovered024).equals(Buffer.from(secret)), 'Shamir 3-of-5 reconstructs');
let n256Rejected = false;
try { cv.cvShamirSplit(Buffer.from(secret), 2, 256); } catch { n256Rejected = true; }
assertCore(n256Rejected, 'Shamir rejects N=256 (u8 coordinate domain)');
let badIndexRejected = false;
try {
  cv.cvShamirCombine([
    { index: 1, data: shares23[0].data },
    { index: 256, data: shares23[1].data },
  ]);
} catch { badIndexRejected = true; }
assertCore(badIndexRejected, 'Shamir combine rejects out-of-range index');

// Rust-generated reference vectors (payload A: 256 KiB (i*31+7)%256 bytes).
assertCore(
  cv.cvGearMatrix()[0].toString(16).padStart(16, '0') === 'ae54d7f999835fc4',
  'SplitMix64 gear matrix matches Rust GEAR[0]'
);
const payloadA = new Uint8Array(256 * 1024);
for (let i = 0; i < payloadA.length; i++) payloadA[i] = (i * 31 + 7) % 256;
const cutsA = cv.cvFastCdcChunk(payloadA, 4096, 16384, 65536)
  .map((c) => `${c.offset}:${c.length}`).join(',');
assertCore(
  cutsA === '0:65536,65536:65536,131072:65536,196608:65536',
  `FastCDC cuts match Rust (got ${cutsA})`
);

// Boundary-shift preservation on the config-text payload shape.
let baseStr = '';
for (let i = 0; i < 5000; i++) {
  const n = String(i).padStart(4, '0');
  baseStr += `CONFIG_KEY_${n}=SECRET_VALUE_LINE_NUMBER_${n}\n`;
}
const baseBytes = te.encode(baseStr);
const baseCuts = cv.cvFastCdcChunk(baseBytes, 4096, 16384, 65536);
assertCore(baseCuts.length >= 10, `expected >= 10 base chunks, got ${baseCuts.length}`);
const insBytes = te.encode('INSERTED_SECURITY_FLAG=TRUE_NEW\n');
const at = baseBytes.length >> 1;
const modBytes = new Uint8Array(baseBytes.length + insBytes.length);
modBytes.set(baseBytes.subarray(0, at), 0);
modBytes.set(insBytes, at);
modBytes.set(baseBytes.subarray(at), at + insBytes.length);
const modCuts = cv.cvFastCdcChunk(modBytes, 4096, 16384, 65536);
const baseSet = new Set(baseCuts.map((c) => Buffer.from(baseBytes.subarray(c.offset, c.offset + c.length)).toString('hex')));
let identical = 0;
for (const c of modCuts) {
  if (baseSet.has(Buffer.from(modBytes.subarray(c.offset, c.offset + c.length)).toString('hex'))) identical++;
}
assertCore(
  identical / baseCuts.length >= 0.80,
  `FastCDC boundary preservation ${(100 * identical / baseCuts.length).toFixed(2)}% < 80%`
);

// No fabricated-data residue: these markers must never return to the page.
const banned = [
  'DEMO-DEAD', 'CAFEBABE', 'CRC32: TEST', 'HMAC-BLAKE2',
  'blake2b_256', '248901422', '0x8f2d', '558.62', '656.84', 'REVEAL SIMULATED',
  'count_distinct_approvals', 'fastcdc::v2020', 'get_dpapi_master_key',
];
for (const marker of banned) {
  assertCore(!js.includes(marker) && !html.includes(marker), `banned fake-data marker present: ${marker}`);
}

console.log('[PASS] Landing crypto core verified (vectors + Rust cross-check + no-fake residue)!');
