[package]
name = "ciphervault-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ciphervault"
path = "src/main.rs"

[dependencies]
clap.workspace = true
colored.workspace = true
anyhow.workspace = true
hex.workspace = true
chrono.workspace = true
rand.workspace = true
sha2.workspace = true
zeroize.workspace = true
ciphervault-crypto = { path = "../../crates/crypto" }
ciphervault-format = { path = "../../crates/format" }
ciphervault-snapshot = { path = "../../crates/snapshot" }
ciphervault-local-store = { path = "../../crates/local-store" }
ciphervault-recovery = { path = "../../crates/recovery" }
ciphervault-storage = { path = "../../crates/storage" }
ciphervault-maintenance = { path = "../../services/maintenance" }
tokio.workspace = true
x25519-dalek.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
axum.workspace = true
futures-util.workspace = true
reqwest = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }

[dev-dependencies]
ciphervault-operator = { path = "../../services/operator" }
ciphervault-agent = { path = "../agent" }

